### ISSUE TITLE
Skip save step if manifest hash has not changed

### ISSUE THREAD

**Issue by jacksongrounded** [buildkite-plugins/cache-buildkite-plugin#72]
Currently if the `save` parameter is configured, a cache will always be saved on the post-command hook.

Saving cache can be a costly operation if the file/folder is large.

It would be good if there was an option to skip saving the cache if it is detected that a cache already exists with the same cache key.

This would mimic what some other CI platforms like CircleCI do:

<img width="1310" alt="image" src="https://github.com/buildkite-plugins/cache-buildkite-plugin/assets/78463386/05585a79-95b5-46ca-859e-fe097db25362">

**Comment by nealchandra** [comment]
Hi @toote -- saw you have a PR open to fix this and it looks like it's close to landing. For our case this step is adding 2m to an otherwise <30s build step and results in CI on Buildkite taking longer than on GitHub Actions, so I'd be eager for the update!

Is there an ETA for when this will land? Thanks very much for the fix!

**Comment by pzeballos** [comment]
> Is there an ETA for when this will land? Thanks very much for the fix!

Done! We'll do a release tomorrow

**Comment by nealchandra** [comment]
Thanks @pzeballos -- I'll wait for the release to integrate my pipeline!

**Comment by nealchandra** [comment]
Hi all -- I tried to integrate this but unfortunately it didn't speed things up much. The issue seems to be that it is always zipping up the directory even if the cache exists. In the case of `.pnpm-store` the zipping operation takes 30-40s so this nullifies the caching benefits. 

Is it possible to reverse the order of operations so that this doesn't occur? Here's the example output from my build:

```

$ /var/lib/buildkite-agent/plugins/buildkite-i-0c1a22a08d7ad2385-2/github-com-buildkite-plugins-cache-buildkite-plugin-v1-1-0/hooks/post-command
--
  | Compressing .pnpm-store with tgz...
  | Cache of file already exists, skipping
```

**Comment by toote** [comment]
@nealchandra I see what you mean, apparently I followed the letter of what you requested and not the spirit of it. From what I can see, though, what you actually need would require more extensive and invasive changes due to the current flow of the code but I will keep it in mind for future changes

**Comment by toote** [comment]
@nealchandra FYI: #78 was opened about your scenario
